classdef AnalyticSignalHCPAgingPar < handle & mlraut.AnalyticSignalHCPAging
    %% line1
    %  line2
    %  
    %  Created 07-Feb-2024 23:37:28 by jjlee in repository /Users/jjlee/MATLAB-Drive/mlraut/src/+mlraut.
    %  Developed on Matlab 23.2.0.2485118 (R2023b) Update 6 for MACA64.  Copyright 2024 John J. Lee.
    
    methods (Static)
        function this = median_twistor()
            this = mlraut.AnalyticSignalHCPAgingPar( ...
                subjects={'HCA9992517_V1_MR'}, ...
                do_7T=false, ...
                do_resting=true, ...
                do_task=false, ...
                do_save=false, ...
                do_save_dynamic=false, ...
                do_save_ciftis=false, ...
                hp_thresh=0.01, ...
                lp_thresh=0.1, ...
                global_signal_regression=true, ...
                tags="AnalyticSignalHCPAgingPar-mean-twistor");

            mats = asrow(glob(fullfile(this.out_dir, 'HCA*_MR/sub-*_ses-*AnalyticSignalHCPAging*.mat')));
            n = length(mats);
            nx = this.num_nodes;
            nfail = 0;

            X_ = zeros(1, nx);
            Y_ = zeros(1, nx);
            Z_ = zeros(1, nx);
            T_ = zeros(1, nx);

            fprintf(stackstr() + "\n");
            for mat = mats
                try
                    tic
                    fprintf("loading %s\n", mat{1});
                    ld = load(mat{1});
                    this_subset = ld.this_subset;
                    try
                        psi = this_subset.bold_signal;
                    catch ME
                        if strcmp(ME.identifier, 'MATLAB:nonExistentField')
                            psi = this_subset.analytic_signal.*this_subset.physio_signal;  % overly normalized in this_subset
                        else
                            rethrow(ME)
                        end
                    end
                    phi = this_subset.physio_signal;
                    X = mean(this.build_final_normalization((psi.*conj(phi) + phi.*conj(psi))/sqrt(2)), 1);
                    Y = mean(this.build_final_normalization((psi.*conj(phi) - phi.*conj(psi))/sqrt(2i)), 1);
                    Z = mean(this.build_final_normalization((psi.*conj(psi) - phi.*conj(phi))/sqrt(2)), 1);
                    T = mean(this.build_final_normalization((psi.*conj(psi) + phi.*conj(phi))/sqrt(2)), 1);

                    X_ = X_ + X/n;
                    Y_ = Y_ + Y/n;
                    Z_ = Z_ + Z/n;
                    T_ = T_ + T/n;
                    toc
                catch ME
                    handwarning(ME)
                    nfail = nfail + 1;
                end
            end
            
            if nfail > 0
                assert(nfail < n)
                X_ = X_*(n/(n - nfail));
                Y_ = Y_*(n/(n - nfail));
                Z_ = Z_*(n/(n - nfail));
                T_ = T_*(n/(n - nfail));
            end

            this.out_dir = fullfile(getenv('HOME'), 'Singularity', 'AnalyticSignalHCPAging_zfs');
            ensuredir(this.out_dir);

            this.write_ciftis( ...
                X_, sprintf('X_as_sub-all_ses-all_%s', this.tags), ...
                do_final_normalization=false, ...
                do_save_dynamic=false);
            this.write_ciftis( ...
                Y_, sprintf('Y_as_sub-all_ses-all_%s', this.tags), ...
                do_final_normalization=false, ...
                do_save_dynamic=false);
            this.write_ciftis( ...
                Z_, sprintf('Z_as_sub-all_ses-all_%s', this.tags), ...
                do_final_normalization=false, ...
                do_save_dynamic=false);
            this.write_ciftis( ...
                T_, sprintf('T_as_sub-all_ses-all_%s', this.tags), ...
                do_final_normalization=false, ...
                do_save_dynamic=false);
            this.write_ciftis( ...
                T_+Z_, sprintf('T+Z_as_sub-all_ses-all_%s', this.tags), ...
                do_final_normalization=false, ...
                do_save_dynamic=false);
        end

        function server_call(cores, opts)
            %% for servers

            arguments
                cores {mustBeScalarOrEmpty} = 2
                opts.N_sub {mustBeScalarOrEmpty} = 725
                opts.flip_globbed logical = true
            end

            % root_dir = '/home/usr/jjlee/mnt/CHPC_hcpdb/packages/unzip/HCP_1200';
            root_dir = fullfile(getenv('SINGULARITY_HOME'), 'HCPAging', 'HCPAgingRec', 'fmriresults01');

            g = glob(fullfile(root_dir, 'HCA*'));
            g = strip(g, filesep);
            g = flip(g); % examine more recent ones first
            g = cellfun(@(x) basename(x), g, UniformOutput=false);
            if opts.flip_globbed
                g = flip(g); % examine more recent ones
            end
            g = g(1:opts.N_sub);
            leng = length(g);
            %for idxg = 1:1
            parfor (idxg = 1:leng, cores)
                try
                    this = mlraut.AnalyticSignalHCPAgingPar( ...
                        subjects=g(idxg), ...
                        do_7T=true, ...
                        do_resting=true, ...
                        do_task=false, ...
                        do_save=true, ...
                        do_save_dynamic=false, ...
                        do_save_ciftis=false, ...
                        hp_thresh=0.01, ...
                        lp_thresh=0.1, ...
                        v_physio=0.1, ...
                        plot_range=1:250, ...
                        global_signal_regression=true, ...
                        tags="AnalyticSignalHCPAgingPar-parcall");
                    call(this);
                catch ME
                    handwarning(ME)
                end
            end
        end

        function [j,c] = cluster_batch_call(globbing_mat, opts)
            %% for clusters running Matlab parallel server

            arguments
                globbing_mat {mustBeFile} = ...
                    fullfile( ...
                    getenv('SINGULARITY_HOME'), 'HCPAging', 'HCPAgingRec', 'fmriresults01', ...
                    'mlraut_AnalyticSignalHCPAgingPar_globbing.mat')
                opts.sub_indices double = [1,3:100]
            end
            ld = load(globbing_mat);
            globbed = asrow(ld.globbed);
            globbed = globbed(opts.sub_indices);

            c = mlraut.CHPC3.propcluster();
            disp(c.AdditionalProperties)
            for g = globbed
                try
                    j = c.batch( ...
                        @mlraut.AnalyticSignalHCPAgingPar.construct_and_call, ...
                        1, ...
                        {g(1)}, ...
                        'CurrentFolder', '.', ...
                        'AutoAddClientPath', false);
                catch ME
                    handwarning(ME)
                end
            end

            % j = c.batch(@mlraut.AnalyticSignalHCPAgingPar.construct_and_call, 1, {}, 'CurrentFolder', '.', 'AutoAddClientPath', false);
        end

        function duration = construct_and_call(subjects, opts)
            arguments
                subjects cell = {'HCA6002236_V1_MR'}
                opts.tasks cell = {'fMRI_CONCAT_ALL'}
                opts.tags {mustBeTextScalar} = "AnalyticSignalHCPAgingPar"
                opts.out_dir {mustBeFolder} = "/scratch/jjlee/Singularity/AnalyticSignalHCPAging"
            end
            
            mlraut.CHPC3.setenvs();
            setenv("VERBOSITY", "1");
            ensuredir(opts.out_dir);
            ensuredir(fullfile(opts.out_dir, subjects{1}));
            diary(fullfile(opts.out_dir, subjects{1}, "diary.log"));
            tic;
            disp("constructing mlraut.AnalyticSignalHCPAgingPar")
            this = mlraut.AnalyticSignalHCPAgingPar( ...
                subjects=subjects, ...
                tasks=opts.tasks, ...
                do_7T=false, ...
                do_plot_networks=false, ...
                do_resting=true, ...
                do_task=false, ...
                do_save=true, ...
                do_save_dynamic=false, ...
                do_save_ciftis=false, ...
                do_save_subset=false, ...
                final_normalization="none", ...
                force_band=false, ...
                global_signal_regression=true, ...
                hp_thresh=0.01, ...
                lp_thresh=0.05, ...
                out_dir=opts.out_dir, ...
                source_physio="iFV", ...
                tags=opts.tags, ...                
                v_physio=50);
            disp("calling this")
            call(this);
            duration = toc;
            fprintf("tic-toc duration: %s seconds", duration);
            diary("off");
        end

        function [j,c] = cluster_par_call(globbing_mat, opts)
            %% for clusters running Matlab parallel server

            arguments
                globbing_mat {mustBeFile} = ...
                    fullfile( ...
                    getenv('SINGULARITY_HOME'), 'HCPAging', 'HCPAgingRec', 'fmriresults01', ...
                    'mlraut_AnalyticSignalHCPAgingPar_globbing.mat')
                opts.sub_indices double = 101:200
                opts.N_max double = 1000
            end
            ld = load(globbing_mat);
            globbed = asrow(ld.globbed);
            globbed = globbed(opts.sub_indices);
            N_sub = length(opts.sub_indices);

            c = mlraut.CHPC3.propcluster();
            disp(c.AdditionalProperties)
            try
                j = c.batch( ...
                    @mlraut.AnalyticSignalHCPAgingPar.par_construct_and_call, ...
                    1, ...
                    {globbed}, ...
                    'Pool', min(N_sub, opts.N_max), ...
                    'CurrentFolder', '.', ...
                    'AutoAddClientPath', false);
            catch ME
                handwarning(ME)
            end
        end

        function duration = par_construct_and_call(subjects, opts)
            arguments
                subjects cell = {'HCA6002236_V1_MR'}
                opts.tasks cell = {'fMRI_CONCAT_ALL'}
                opts.tags {mustBeTextScalar} = "AnalyticSignalHCPAgingPar"
                opts.out_dir {mustBeFolder} = "/scratch/jjlee/Singularity/AnalyticSignalHCPAging"
            end
            
            duration = [];

            parfor sidx = 1:length(subjects)            
                mlraut.CHPC3.setenvs();
                ensuredir(opts.out_dir); %#ok<PFBNS>
                setenv("VERBOSITY", "1");
                ensuredir(fullfile(opts.out_dir, subjects{sidx})); 
                diary(fullfile(opts.out_dir, subjects{sidx}, "diary.log")); 
                tic;
                disp("constructing mlraut.AnalyticSignalHCPAgingPar")
                this = mlraut.AnalyticSignalHCPAgingPar( ...
                    subjects=subjects(sidx), ...
                    tasks=opts.tasks, ...
                    do_7T=false, ...
                    do_plot_networks=false, ...
                    do_resting=true, ...
                    do_task=false, ...
                    do_save=true, ...
                    do_save_dynamic=false, ...
                    do_save_ciftis=false, ...
                    do_save_subset=false, ...
                    final_normalization="none", ...
                    force_band=false, ...
                    global_signal_regression=true, ...
                    hp_thresh=0.01, ...
                    lp_thresh=0.05, ...
                    out_dir=opts.out_dir, ...
                    source_physio="iFV", ...
                    tags=opts.tags, ...
                    v_physio=50);
                disp("calling this")
                call(this);
                fprintf("tic-toc duration: %s seconds", duration);
                diary("off");
            end
        end
    end

    methods
        function this = AnalyticSignalHCPAgingPar(varargin)
            this = this@mlraut.AnalyticSignalHCPAging(varargin{:});
        end
    end
    
    %  Created with mlsystem.Newcl, inspired by Frank Gonzalez-Morphy's newfcn.
end
